# Generated by Django 6.0.1 on 2026-02-01
from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('finances', 'Category')
    
    default_categories = [
        {'name': 'Продукти', 'description': 'Витрати на продукти харчування'},
        {'name': 'Авто', 'description': 'Витрати на автомобіль: пальне, ремонт, страховка'},
        {'name': 'Одяг', 'description': 'Витрати на одяг та взуття'},
        {'name': 'Розваги', 'description': 'Витрати на розваги та відпочинок'},
        {'name': 'Здоровя', 'description': 'Витрати на медицину та здоровя'},
        {'name': 'Комунальні', 'description': 'Оплата комунальних послуг'},
        {'name': 'Транспорт', 'description': 'Витрати на громадський транспорт'},
        {'name': 'Інше', 'description': 'Інші витрати'},
    ]
    
    for category_data in default_categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            defaults={'description': category_data['description']}
        )


def remove_default_categories(apps, schema_editor):
    Category = apps.get_model('finances', 'Category')
    default_names = ['Продукти', 'Авто', 'Одяг', 'Розваги', 'Здоровя', 'Комунальні', 'Транспорт', 'Інше']
    Category.objects.filter(name__in=default_names).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('finances', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]